stages:
  - build
#  - test

build-debian-buster-GCC8-mpiandsmp:
  image: gitdocker.physik.hu-berlin.de/sol/exciting:debian-buster-GCC8
  stage: build
  # Tags assign the gitlab runners. 
  tags: 
    - docker
  script:
    - cp build/platforms/make.inc.gfortran build/make.inc 
    - make mpiandsmp
  allow_failure: false

#build-debian-buster-Intel2021-mpiandsmp:
#image: gitdocker.physik.hu-berlin.de/sol/exciting:debian-buster-intel2021
#stage: build
#tags: 
#  - docker
#script:
#  - cp build/platforms/make.inc.ifort build/make.inc
#  - source /opt/intel/oneapi/setvars.sh
#  - make mpiandsmp
#allow_failure: true
